name: 信息查询

on:
  workflow_dispatch: # 手动触发
  push:
    branches:
      - main1
  schedule:
    - cron: '6 0-15 * * *'


jobs:
  Info1:
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
          node-version: 16.x
    - name: npm install
      run : |
        npm install
        npm install axios --save

    - name: "运行脚本"
      env:
        TZ: Asia/Shanghai  # 设置时区
        CLCOOKIE: ${{ secrets.CLCOOKIE1 }}
        UA: ${{ secrets.UA1 }}
        CLREPLYCOUNT: ${{ secrets.CLREPLYCOUNT }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}

      run: |
        node cl_info.js
        
  Info2:
    needs: Info1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
          node-version: 16.x
    - name: npm install
      run : |
        npm install
        npm install axios --save

    - name: "运行脚本"
      env:
        TZ: Asia/Shanghai  # 设置时区
        CLCOOKIE: ${{ secrets.CLCOOKIE2 }}
        UA: ${{ secrets.UA2 }}
        CLREPLYCOUNT: ${{ secrets.CLREPLYCOUNT }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}

      run: |
        node cl_info.js
  Info3:
    needs: Info2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
          node-version: 16.x
    - name: npm install
      run : |
        npm install
        npm install axios --save

    - name: "运行脚本"
      env:
        TZ: Asia/Shanghai  # 设置时区
        CLCOOKIE: ${{ secrets.CLCOOKIE3 }}
        UA: ${{ secrets.UA3 }}
        CLREPLYCOUNT: ${{ secrets.CLREPLYCOUNT }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}

      run: |
        node cl_info.js
  Info4:
    needs: Info3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
          node-version: 16.x
    - name: npm install
      run : |
        npm install
        npm install axios --save

    - name: "运行脚本"
      env:
        TZ: Asia/Shanghai  # 设置时区
        CLCOOKIE: ${{ secrets.CLCOOKIE4 }}
        UA: ${{ secrets.UA4 }}
        CLREPLYCOUNT: ${{ secrets.CLREPLYCOUNT }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}

      run: |
        node cl_info.js
  Info5:
    needs: Info3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
          node-version: 16.x
    - name: npm install
      run : |
        npm install
        npm install axios --save

    - name: "运行脚本"
      env:
        TZ: Asia/Shanghai  # 设置时区
        CLCOOKIE: ${{ secrets.CLCOOKIE5 }}
        UA: ${{ secrets.UA5 }}
        CLREPLYCOUNT: ${{ secrets.CLREPLYCOUNT }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}

      run: |
        node cl_info.js
  Info6:
    needs: Info3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
          node-version: 16.x
    - name: npm install
      run : |
        npm install
        npm install axios --save

    - name: "运行脚本"
      env:
        TZ: Asia/Shanghai  # 设置时区
        CLCOOKIE: ${{ secrets.CLCOOKIE6 }}
        UA: ${{ secrets.UA6 }}
        CLREPLYCOUNT: ${{ secrets.CLREPLYCOUNT }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}

      run: |
        node cl_info.js
  Info7:
    needs: Info3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
          node-version: 16.x
    - name: npm install
      run : |
        npm install
        npm install axios --save

    - name: "运行脚本"
      env:
        TZ: Asia/Shanghai  # 设置时区
        CLCOOKIE: ${{ secrets.CLCOOKIE7 }}
        UA: ${{ secrets.UA7 }}
        CLREPLYCOUNT: ${{ secrets.CLREPLYCOUNT }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}

      run: |
        node cl_info.js
