name: 回帖

on:
  workflow_dispatch: # 手动触发
  push:
    branches:
      - main1
  schedule:
    - cron: '26 4 * * *'


jobs:

  Info3:
    #needs: Info2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
          node-version: 16.x
    - name: npm install
      run : |
        npm install
        npm install axios --save

    - name: "运行脚本"
      env:
        CLCOOKIE: ${{ secrets.CLCOOKIE3 }}
        UA: ${{ secrets.UA3 }}
        CLREPLYCOUNT: ${{ secrets.CLREPLYCOUNT }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}

      run: |
        node cl_reply.js
  Info4:
    #needs: Info3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
          node-version: 16.x
    - name: npm install
      run : |
        npm install
        npm install axios --save

    - name: "运行脚本"
      env:
        CLCOOKIE: ${{ secrets.CLCOOKIE4 }}
        UA: ${{ secrets.UA4 }}
        CLREPLYCOUNT: ${{ secrets.CLREPLYCOUNT }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}

      run: |
        node cl_reply.js

  Info5:
    #needs: Info2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
          node-version: 16.x
    - name: npm install
      run : |
        npm install
        npm install axios --save

    - name: "运行脚本"
      env:
        CLCOOKIE: ${{ secrets.CLCOOKIE5 }}
        UA: ${{ secrets.UA5 }}
        CLREPLYCOUNT: ${{ secrets.CLREPLYCOUNT }}
        #ISNEWBODY: ${{ secrets.NEWBODY }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}

      run: |
        node cl_reply.js
  Info6:
    #needs: Info3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
          node-version: 16.x
    - name: npm install
      run : |
        npm install
        npm install axios --save

    - name: "运行脚本"
      env:
        CLCOOKIE: ${{ secrets.CLCOOKIE6 }}
        UA: ${{ secrets.UA6 }}
        #ISNEWBODY: ${{ secrets.NEWBODY }}
        CLREPLYCOUNT: ${{ secrets.CLREPLYCOUNT }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}

      run: |
        node cl_reply.js

